name: gossip
channels:
  - defaults
dependencies:
  - python=3.8.5
  - pip=20.3
  - numpy=1.23.1
  - pip:
    - click==8.1.7
    - colorama==0.4.6
    - flask==2.3.3
    - greenlet==2.0.2
    - idna==3.4
    - importlib-metadata==6.8.0
    - itsdangerous==2.1.2
    - jieba==0.42.1
    - Jinja2==3.1.2
    - joblib==1.3.2
    - MarkupSafe==2.1.3
    - numpy==1.24.4
    - pandas==2.0.3
    - PyMySQL==1.1.0
    - python-dateutil==2.8.2
    - pytz==2023.3
    - requests==2.31.0
    - scikit-learn==1.3.0
    - scipy==1.10.1
    - six==1.16.0
    - snownlp==0.12.3
    - SQLAlchemy==2.0.20
    - threadpoolctl==3.2.0
    - typing-extensions==4.7.1
    - tzdata==2023.3
    - urllib3==2.0.4
    - Werkzeug==2.3.7
    - zipp==3.16.2
    - cryptography==42.0.5
    - pillow==6.2.1